export let products = [
  {
    id: 1,
    name: "더블 비프 미트칠리 버거",
    en_name: "Double Beef Meat Chili Burger",
    data_type: "recommended_menu burger&set main",
    content_text:
      "진한 고기맛 살리는 미트칠리 소스에 상큼한 사워크림,<br />순쇠고기 100% 패티 2장과 짭조롬한 치즈와 베이컨까지!<br />연말엔 더블 비프 미트칠리 버거!",
    M_img:
      "./menu_imgs/buger_imgs/set_menu/Double_beef_meat_chillie_burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Double_beef_meat_chillie_burger.png",
    L_price: 10900,
    M_price: 10200,
    S_price: 8300,
    large_set_Kcal: "1049~1243",
    set_Kcal: "976~1115",
    Kcal: 652,
    weight: "239g",
    suger: "11/11",
    protein: "31/57",
    saturated_fat: "14/93",
    sodium: "1171/59",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country:
      "쇠고기:호주산<br />돼지고기(베이컨):외국산(아일랜드,스페인,캐나다)",
  },
  {
    id: 2,
    name: "미트칠리 비엘티 버거",
    en_name: "Meat Chili BLT Burger",
    data_type: "recommended_menu burger&set main",
    content_text:
      "진한 고기맛 살리는 미트칠리 소스에 상큼한 사워크림,<br />신선한 양상추와 토마토까지!<br />미트칠리 BLT 버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/Meat_Chili_BLT_Burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Meat_Chili_BLT_Burger.png",
    L_price: 10400,
    M_price: 9700,
    S_price: 7800,
    large_set_Kcal: "951~1144",
    set_Kcal: "877~1017",
    Kcal: 554,
    weight: "271g",
    suger: "12/12",
    protein: "24/43",
    saturated_fat: "11/72",
    sodium: "1080/54",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country:
      "쇠고기:호주산<br />돼지고기(베이컨):외국산(아일랜드,스페인,캐나다)",
  },
  {
    id: 3,
    name: "더블 쿼터 파운드 버거",
    en_name: "Double Quarter Pounder® with Cheese",
    data_type: "recommended_menu burger&set",
    content_text:
      "좋아하는건 더 많이 즐기시라고, 두 배 이상 커진 1/4 파운드<br />비프 패티가 두 장 (226그램)! 육즙이 풍부한 고기 맛을 그대로 살린 100% 순 쇠고기 패티 두 장과<br />치즈 두 장이 입안 가득 완벽하게 조화되는 놀라운 맛",
    M_img:
      "./menu_imgs/buger_imgs/set_menu/Double_quarter_pound_cheeseburger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Double_quarter_pound_cheeseburger.png",
    L_price: 11100,
    M_price: 10400,
    S_price: 8200,
    large_set_Kcal: "1168~1361",
    set_Kcal: "1094~1233",
    Kcal: 770,
    weight: "275g",
    suger: "10/10",
    protein: "50/91",
    saturated_fat: "20/136",
    sodium: "1151/58",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
  {
    id: 4,
    name: "쿼터 파운드 치즈 버거",
    en_name: "Quarter Pounder® with Cheese",
    data_type: "recommended_menu burger&set",
    content_text:
      "쿼터파운더라는 이름에서 알 수 있듯이 두 배 이상 커진 1/4파운드(113그램) 비프와 부드러운 치즈 두 장의 환상궁합!<br />두툼한 순 쇠고기 패티와 신선한 치즈의 풍부한 맛으로 세계적으로 사랑받고 있는<br />맥도날드의 대표적인 프리미엄 버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/Quarter_pound_cheeseburger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Quarter_pound_cheeseburger.png",
    L_price: 9600,
    M_price: 8900,
    S_price: 6300,
    large_set_Kcal: "933~1127",
    set_Kcal: "859~999",
    Kcal: 536,
    weight: "198g",
    suger: "10/10",
    protein: "31/56",
    saturated_fat: "13/86",
    sodium: "966/48",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
  {
    id: 5,
    name: "맥크리스피™ 디럭스 버거",
    en_name: "McCrispy™ Deluxe Burger",
    data_type: "recommended_menu burger&set main",
    content_text:
      "100% 통닭다리살 겉바속촉 케이준 치킨 패티,<br />촉촉한 포테이토 브리오쉬 번, 스페셜 스모키 소스가<br />선사하는 놀랍도록 새로운 맛의 치킨 버거!",
    M_img: "./menu_imgs/buger_imgs/set_menu/Maccrispy_Deluxe_Burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Maccrispy_Deluxe_Burger.png",
    L_price: 9900,
    M_price: 9200,
    S_price: 7600,
    large_set_Kcal: "1011~1205",
    set_Kcal: "938~1077",
    Kcal: 614,
    weight: "269g",
    suger: "15/15",
    protein: "23/43",
    saturated_fat: "5/31",
    sodium: "1296/65",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기: 브라질산 또는 태국산",
  },
  {
    id: 6,
    name: "맥크리스피™ 클래식 버거",
    en_name: "McCrispy™ Classic Burger",
    data_type: "recommended_menu burger&set main",
    content_text:
      "100% 통닭다리살 겉바속촉 케이준 치킨 패티!<br />치킨 버거 본연의 맛에 충실한 클래식 버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/Maccrispy_Classic_Burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Maccrispy_Classic_Burger.png",
    L_price: 9400,
    M_price: 8700,
    S_price: 6700,
    large_set_Kcal: "1000~1193",
    set_Kcal: "926~1066",
    Kcal: 603,
    weight: "203g",
    suger: "13/13",
    protein: "23/41",
    saturated_fat: "5/30",
    sodium: "1294/65",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기: 브라질산 또는 태국산",
  },
  {
    id: 7,
    name: "빅맥",
    en_name: "Big Mac",
    data_type: "recommended_menu burger&set",
    content_text:
      "100% 순 쇠고기 패티 두 장에 빅맥®만의 특별한 소스.<br />입안에서 살살 녹는 치즈와 신선한 양상추, 양파, 그리고 피클까지.<br />50년 넘게 전 세계인의 입맛을 사로 잡은 버거의 대명사.",
    M_img: "./menu_imgs/buger_imgs/set_menu/BigMac.png",
    S_img: "./menu_imgs/buger_imgs/buger/BigMac.png",
    L_price: 8900,
    M_price: 8200,
    S_price: 6300,
    large_set_Kcal: "980~1173",
    set_Kcal: "906~1045",
    Kcal: 582,
    weight: "223g",
    suger: "8/8",
    protein: "27/49",
    saturated_fat: "11/71",
    sodium: "902/45",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기: 호주산",
  },
  {
    id: 8,
    name: "트리플 치즈 버거",
    en_name: "Triple Cheeseburger",
    data_type: "burger&set main",
    content_text:
      "부드러운 치즈와 풍부한 육즙의 패티를<br />세배 더 진하게 즐길 수 있는 트리플 치즈버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/Triple_cheeseburger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Triple_cheeseburger.png",
    L_price: 9200,
    M_price: 8500,
    S_price: 6600,
    large_set_Kcal: "1037~1231",
    set_Kcal: "963~1103",
    Kcal: 640,
    weight: "219g",
    suger: "9/9",
    protein: "36/65",
    saturated_fat: "17/115",
    sodium: "1230/61",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기: 호주산",
  },
  {
    id: 9,
    name: "더블 불고기 버거",
    en_name: "Double Bulgogi Burger",
    data_type: "burger&set",
    content_text:
      "진한 불고기 소스의 패티가 두 장!<br />여기에 고소한 치즈와 마요네즈,<br />신선한 양상추를 곁들인 깊고 풍부한 맛.",
    M_img: "./menu_imgs/buger_imgs/set_menu/Double_Bulgogi_Burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Double_Bulgogi_Burger.png",
    L_price: 8000,
    M_price: 7300,
    S_price: 5400,
    large_set_Kcal: "1032~1226",
    set_Kcal: "959~1098",
    Kcal: 635,
    weight: "237g",
    suger: "15/15",
    protein: "26/48",
    saturated_fat: "13/86",
    sodium: "997/50",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "돼지고기: 국내산",
  },
  {
    id: 10,
    name: "맥스파이시 상하이 버거",
    en_name: "McSpicy® Shanghai Burger",
    data_type: "burger&set",
    content_text:
      "매콤한 시즈닝을 입힌 100% 닭가슴 통살 위에<br />아삭아삭한 양상추와 신선한 토마토~<br />겉은 바삭, 속은 부드러운 치킨 패티의 매콤함으로<br />입맛도 기분도 화끈하게!",
    M_img: "./menu_imgs/buger_imgs/set_menu/McSpicy_Shanghai_Burge.png",
    S_img: "./menu_imgs/buger_imgs/buger/McSpicy_Shanghai_Burge.png",
    L_price: 8900,
    M_price: 8200,
    S_price: 6300,
    large_set_Kcal: "898~1092",
    set_Kcal: "825~964",
    Kcal: 501,
    weight: "246g",
    suger: "9/9",
    protein: "24/44",
    saturated_fat: "3/17",
    sodium: "1102/55",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기:국내산",
  },
  {
    id: 11,
    name: "1955 버거",
    en_name: "1955® Burger",
    data_type: "burger&set",
    content_text:
      "113g 두툼한 순 쇠고기 패티,<br />특별한 1955 소스에 깊은 풍미의 그릴드 어니언까지!<br />맥도날드가 처음 생긴 1955년의 맛을 담은<br />영원한 오리지널 1955 버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/1955_burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/1955_burger.png",
    L_price: 9800,
    M_price: 9100,
    S_price: 7200,
    large_set_Kcal: "970~1163",
    set_Kcal: "896~1035",
    Kcal: 572,
    weight: "264g",
    suger: "15/15",
    protein: "29/53",
    saturated_fat: "10/68",
    sodium: "930/47",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country:
      "쇠고기:호주산<br />돼지고기(베이컨):외국산(아일랜드,스페인,캐나다)",
  },
  {
    id: 12,
    name: "맥치킨 모짜렐라",
    en_name: "McChicken® Mozzarella",
    data_type: "burger&set",
    content_text:
      "든든한 맥치킨에 골든 모짜렐라 치즈 스틱 2개와<br />매콤한 아라비아따 소스를 더해<br />강렬하게 재탄생한 맥치킨 모짜렐라!",
    M_img: "./menu_imgs/buger_imgs/set_menu/McChicken_mozzarella.png",
    S_img: "./menu_imgs/buger_imgs/buger/McChicken_mozzarella.png",
    L_price: 9200,
    M_price: 8500,
    S_price: 5800,
    large_set_Kcal: "1140~1334",
    set_Kcal: "1066~1206",
    Kcal: 743,
    weight: "293g",
    suger: "18/18",
    protein: "31/56",
    saturated_fat: "7/47",
    sodium: "1742/87",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기:국내산",
  },
  {
    id: 13,
    name: "맥치킨",
    en_name: "McChicken",
    data_type: "burger&set",
    content_text:
      "바삭한 치킨 패티, 고소한 화이트 마요 소스와<br />아삭한 양상추가 함께!<br />더 업그레이드된 맛으로 돌아온 맥치킨",
    M_img: "./menu_imgs/buger_imgs/set_menu/McChicken_burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/McChicken_burger.png",
    L_price: 7000,
    M_price: 6300,
    S_price: 4300,
    large_set_Kcal: "921~1114",
    set_Kcal: "847~986",
    Kcal: 523,
    weight: "206g",
    suger: "7/7",
    protein: "21/38",
    saturated_fat: "3/21",
    sodium: "1084/54",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기:국내산",
  },
  {
    id: 14,
    name: "에그 불고기 버거",
    en_name: "Egg Bulgogi Burger",
    data_type: "burger&set",
    content_text:
      "불고기 버거에 국내산 1+등급 계란을 더해<br />맛의 정점을 찍다!",
    M_img: "./menu_imgs/buger_imgs/set_menu/egg_Bulgogi_burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/egg_Bulgogi_burger.png",
    L_price: 7600,
    M_price: 6900,
    S_price: 4700,
    large_set_Kcal: "889~1082",
    set_Kcal: "815~954",
    Kcal: 491,
    weight: "222g",
    suger: "14/14",
    protein: "21/39",
    saturated_fat: "7/48",
    sodium: "748/37",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "돼지고기:국내산",
  },
  {
    id: 15,
    name: "불고기 버거",
    en_name: "Bulgogi Burger",
    data_type: "burger&set",
    content_text:
      "한국인의 입맛에 딱 맞는 불고기 소스에<br />잘 재운 패티와 고소한 마요네즈,<br />신선한 양상추의 맛있는 조합.",
    M_img: "./menu_imgs/buger_imgs/set_menu/Bulgogi_Burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Bulgogi_burger.png",
    L_price: 6900,
    M_price: 6200,
    S_price: 4000,
    large_set_Kcal: "806~999",
    set_Kcal: "732~872",
    Kcal: 409,
    weight: "167g",
    suger: "14/14",
    protein: "14/26",
    saturated_fat: "6/37",
    sodium: "670/33",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "돼지고기:국내산",
  },
  {
    id: 16,
    name: "슈슈 버거",
    en_name: "Supreme Shrimp Burger",
    data_type: "burger&set",
    M_img: "./menu_imgs/buger_imgs/set_menu/Shushu_burger.png",
    content_text: "탱~글한 통새우살 가득~ 슈슈 버거!",
    S_img: "./menu_imgs/buger_imgs/buger/Shushu_burger.png",
    L_price: 8000,
    M_price: 7300,
    S_price: 5500,
    large_set_Kcal: "806~999",
    set_Kcal: "732~872",
    Kcal: 409,
    weight: "224g",
    suger: "13/13",
    protein: "12/22",
    saturated_fat: "1.7/12",
    sodium: "808/40",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "새우패티:태국산",
  },
  {
    id: 17,
    name: "슈비 버거",
    en_name: "Shrimp Beef Burger",
    data_type: "burger&set",
    content_text:
      "탱~글한 통새우살에 비프 패티를 더해 푸짐하게~<br />슈비 버거",
    M_img: "./menu_imgs/buger_imgs/set_menu/Shubi_burger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Shubi_burger.png",
    L_price: 9800,
    M_price: 9100,
    S_price: 6600,
    large_set_Kcal: "937~1130",
    set_Kcal: "863~1003",
    Kcal: 540,
    weight: "269g",
    suger: "15/15",
    protein: "20/36",
    saturated_fat: "5/35",
    sodium: "1001/50",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "새우패티:태국산<br />쇠고기: 호주산",
  },
  {
    id: 18,
    name: "베이컨 토마토 디럭스",
    en_name: "Bacon Tomato Deluxe",
    data_type: "burger&set",
    content_text:
      "두 장의 100% 순 쇠고기 패티에 그릴에 구워 더욱 고소한 1장의 베이컨을 얹고,<br />신선한 토마토와 양상추, 매콤달콤한 스위트 칠리 소스, 치즈, 마요네즈를 더해<br />더욱 풍부하고 신선한 맛의 프리미엄 버거.",
    M_img: "./menu_imgs/buger_imgs/set_menu/Bacon_Tomato_Deluxe.png",
    S_img: "./menu_imgs/buger_imgs/buger/Bacon_Tomato_Deluxe.png",
    L_price: 9700,
    M_price: 9000,
    S_price: 6600,
    large_set_Kcal: "967~1161",
    set_Kcal: "894~1033",
    Kcal: 570,
    weight: "247g",
    suger: "14/14",
    protein: "29/52",
    saturated_fat: "11/72",
    sodium: "933/47",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country:
      "쇠고기: 호주산<br />돼지고기(베이컨):외국산(아일랜드,스페인,캐나다)",
  },
  {
    id: 19,
    name: "치즈 버거",
    en_name: "Cheeseburger",
    data_type: "burger&set",
    content_text:
      "고소하고 부드러운 치즈와 100% 순 쇠고기 패티,<br />맥도날드만의 심플한 클래식 치즈버거.",
    M_img: "./menu_imgs/buger_imgs/set_menu/Cheeseburger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Cheeseburger.png",
    L_price: 6700,
    M_price: 6000,
    S_price: 3600,
    large_set_Kcal: "715~908",
    set_Kcal: "641~781",
    Kcal: 318,
    weight: "115g",
    suger: "7/7",
    protein: "16/29",
    saturated_fat: "6/40",
    sodium: "612/31",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
  {
    id: 20,
    name: "더블 치즈 버거",
    en_name: "Double Cheeseburger",
    data_type: "burger&set",
    content_text:
      "고소하고 부드러운 치즈와<br />100% 순 쇠고기 패티가 두개<br />맥도날드만의 더블 치즈버거!!",
    M_img: "./menu_imgs/buger_imgs/set_menu/Double_Cheeseburger.png",
    S_img: "./menu_imgs/buger_imgs/buger/Double_Cheeseburger.png",
    L_price: 8000,
    M_price: 7300,
    S_price: 5500,
    large_set_Kcal: "876~1070",
    set_Kcal: "802~942",
    Kcal: 479,
    weight: "167g",
    suger: "8/8",
    protein: "27/49",
    saturated_fat: "12/78",
    sodium: "896/45",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
  {
    id: 21,
    name: "햄버거",
    en_name: "Hamburger",
    data_type: "burger&set",
    content_text:
      "00% 순 쇠고기 패티에 상큼한 피클과 양파,<br />기본에 충실한 맥도날드 햄버거.",
    M_img: "./menu_imgs/buger_imgs/buger/Hamburger.png",
    M_price: 5500,
    Kcal: 266,
    weight: "101g",
    suger: "7/7",
    protein: "13/24",
    saturated_fat: "3/23",
    sodium: "450/22",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
  {
    id: 22,
    name: "토마토 치킨 스낵랩",
    en_name: "Tomato Chicken Snack Wrap",
    data_type: "recommended_menu snak&side",
    content_text:
      "상큼한 토마토와 바삭한 치킨의 조합!<br />매콤한 스파이시 어니언 소스로 더 맛있게!",
    M_img: "./menu_imgs/snack_side/Tomato_chicken_snack_wrap.png",
    M_price: 3800,
    Kcal: 278,
    weight: "144g",
    suger: "7/7",
    protein: "11/20",
    saturated_fat: "3/19",
    sodium: "826/41",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기:국내산",
  },
  {
    id: 23,
    name: "상하이 치킨 스낵랩",
    en_name: "Shanghai Chicken Snack Wrap",
    data_type: "snak&side",
    content_text:
      "매콤한 치킨에 달콤한 화이트 마요 소스로 매콤달콤하게!<br />베이컨에 양상추, 또띠아까지 어우러져<br />씹는 맛까지 즐겁다!",
    M_img: "./menu_imgs/snack_side/Tomato_chicken_snack_wrap.png",
    M_price: 3800,
    Kcal: 303,
    weight: "112g",
    suger: "3/3",
    protein: "12/21",
    saturated_fat: "3.7/25",
    sodium: "812/41",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country:
      "닭고기:국내산<br />돼지고기(베이컨):외국산(아일랜드,스페인,캐나다)",
  },
  {
    id: 24,
    name: "코울슬로",
    en_name: "Coleslaw",
    data_type: "snak&side",
    content_text:
      "양배추, 당근, 양파가 상큼하고 크리미한 마요 드레싱과<br />어우러져 아삭하게 씹히는 샐러드",
    M_img: "./menu_imgs/snack_side/Coleslaw.png",
    M_price: 2700,
    Kcal: 179,
    weight: "100g",
    suger: "18/18",
    protein: "1/2",
    saturated_fat: "1/10",
    sodium: "307/15",
    allergy:
      "알레르기 유발 가능 식재료 (난류,대두,조개,굴)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 25,
    name: "골든 모짜렐라 치즈스틱 4조각",
    en_name: "Golden Mozzarella Cheese Sticks 4pcs",
    data_type: "snak&side",
    content_text:
      "속이 꽉 찬 황금빛 바삭함!<br />자연 모짜렐라 치즈로 빈틈 없이 고소한 맥도날드 치즈스틱을<br />2조각과 4조각으로 다양하게 즐겨보세요!",
    M_img: "./menu_imgs/snack_side/Golden_mozzarella_cheese_stick_4piece.png",
    M_price: 5000,
    Kcal: 330,
    weight: "94g",
    suger: "2/2",
    protein: "16/29",
    saturated_fat: "8.4/56",
    sodium: "577/29",
    allergy:
      "알레르기 유발 가능 식재료 (우유,대두,밀)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 26,
    name: "골든 모짜렐라 치즈스틱 2조각",
    en_name: "Golden Mozzarella Cheese Sticks 2pcs",
    data_type: "snak&side",
    content_text:
      "속이 꽉 찬 황금빛 바삭함!<br />자연 모짜렐라 치즈로 빈틈 없이 고소한 맥도날드 치즈스틱을<br />2조각과 4조각으로 다양하게 즐겨보세요!",
    M_img: "./menu_imgs/snack_side/Golden_mozzarella_cheese_stick_2piece.png",
    M_price: 3300,
    Kcal: 165,
    weight: "47g",
    suger: "1/1",
    protein: "8/14",
    saturated_fat: "4.2/28",
    sodium: "288/14",
    allergy:
      "알레르기 유발 가능 식재료 (우유,대두,밀)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 27,
    name: "맥너겟®6조각",
    en_name: "McNuggets® 6pcs",
    data_type: "snak&side",
    content_text:
      "바삭하고 촉촉한 치킨이 한 입에 쏙!<br />다양한 소스로 입맛에 맞게 즐겨보세요!",
    S_img: "./menu_imgs/snack_side/McNugget_6piece.png",
    M_img: "./menu_imgs/snack_side/McNugget_6piece.png",
    L_price: 8000,
    M_price: 7300,
    S_price: 4600,
    large_set_Kcal: "642~835",
    set_Kcal: "568~707",
    Kcal: 244,
    weight: "95g",
    suger: "0/0",
    protein: "15/27",
    saturated_fat: "2/11",
    sodium: "553/28",
    allergy:
      "알레르기 유발 가능 식재료 (대두,밀,닭고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 28,
    name: "맥너겟®4조각",
    en_name: "McNuggets® 4pcs",
    data_type: "snak&side",
    content_text:
      "바삭하고 촉촉한 치킨이 한 입에 쏙!<br />다양한 소스로 입맛에 맞게 즐겨보세요!",
    M_img: "./menu_imgs/snack_side/McNugget_4piece.png",
    M_price: 3400,
    Kcal: 163,
    weight: "64g",
    suger: "0/0",
    protein: "10/18",
    saturated_fat: "1.1/7",
    sodium: "369/18",
    allergy:
      "알레르기 유발 가능 식재료 (대두,밀,닭고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 29,
    name: "맥스파이시®치킨 텐더",
    en_name: "McSpicy® Chicken Tenders",
    data_type: "snak&side",
    content_text:
      "부드러운 100% 닭안심살을 스파이시 시즈닝으로<br />매콤 바삭하게 튀겨낸 치킨 텐더!<br />2가지 소스로 입맛에 맞게 즐겨보세요!",
    M_img: "./menu_imgs/snack_side/McSpicy_Chicken_Tender_2piece.png",
    M_price: 3500,
    Kcal: 197,
    weight: "-",
    suger: "-",
    protein: "-",
    saturated_fat: "-",
    sodium: "-",
    allergy:
      "알레르기 유발 가능 식재료 (대두,밀,닭고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "닭고기:국내산",
  },
  {
    id: 30,
    name: "후렌치 후라이",
    en_name: "French Fries",
    data_type: "snak&side",
    content_text:
      "통으로 썰어낸 감자를 맥도날드만의 노하우로 튀겨낸 남다른 맛과 바삭함!<br />맥도날드의 역사가 담긴 월드 클래스 후렌치 후라이",
    M_img: "./menu_imgs/snack_side/French_fries_medium.png",
    S_img: "./menu_imgs/snack_side/French_fries_small.png",
    L_price: 3800,
    M_price: 3000,
    S_price: 2300,
    large_set_Kcal: "397",
    set_Kcal: "324",
    Kcal: 210,
    weight: "114g",
    suger: "0/0",
    protein: "5/10",
    saturated_fat: "1/7",
    sodium: "282/14",
    allergy:
      "알레르기 유발 가능 식재료 (대두)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 31,
    name: "디핑소스-스위트 앤 사워소스",
    en_name: "Sweet and sour sauce",
    M_img: "./menu_imgs/snack_side/Sweet_chili_sauce.png",
    data_type: "snak&side",
    M_price: 300,
    Kcal: 40,
    weight: "25g",
    suger: "8/8",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "138/7",
    allergy:
      "알레르기 유발 가능 식재료 (대두, 밀, 아황산류)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 32,
    name: "디핑소스-스위트 칠리 소스",
    en_name: "Sweet chili sauce",
    M_img: "./menu_imgs/snack_side/Sweet_chili_sauce.png",
    data_type: "snak&side",
    M_price: 300,
    Kcal: 52,
    weight: "25g",
    suger: "9/9",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "204/10",
    allergy:
      "알레르기 유발 가능 식재료 (토마토)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 33,
    name: "디핑소스-케이준 소스",
    en_name: "Cajun sauce",
    M_img: "./menu_imgs/snack_side/Cajun_sauce.png",
    data_type: "snak&side",
    M_price: 300,
    Kcal: 79,
    weight: "22g",
    suger: "2/2",
    protein: "0/0",
    saturated_fat: "1.1/7",
    sodium: "124/6",
    allergy:
      "알레르기 유발 가능 식재료 (난류, 대두, 굴)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 34,
    name: "제주 한라봉 칠러",
    en_name: "Jeju Hallabong Chiller",
    data_type: "recommended_menu drink",
    content_text: "제주 한라봉의<br />상큼새콤한 맛과 향을 즐겨보세요!",
    S_img: "./menu_imgs/drink/Jeju_Hallabong_Chiller.png",
    M_img: "./menu_imgs/drink/Jeju_Hallabong_Chiller_large.png",
    L_price: 4700,
    M_price: 3700,
    S_price: 2900,
    large_set_Kcal: 365,
    set_Kcal: 236,
    Kcal: 165,
    weight: "400ml",
    suger: "40/40",
    protein: "1/1",
    saturated_fat: "0/0",
    sodium: "48/2",
  },
  {
    id: 35,
    name: "자두 천도복숭아 칠러",
    en_name: "Plum Peach Chiller",
    data_type: "recommended_menu drink",
    content_text:
      "상콤한 자두와 달콤한 천도복숭아의 만남!<br />자두 천도복숭아 칠러",
    S_img: "./menu_imgs/drink/Plum_Cheondo_Peach_Chiller.png",
    M_img: "./menu_imgs/drink/Plum_Cheondo_Peach_Chiller_large.png",
    L_price: 4700,
    M_price: 3700,
    S_price: 2900,
    large_set_Kcal: 349,
    set_Kcal: 237,
    Kcal: 175,
    weight: "-",
    suger: "-",
    protein: "-",
    saturated_fat: "-",
    sodium: "-",
  },
  {
    id: 36,
    name: "코카-콜라",
    en_name: "Coca-Cola",
    data_type: "drink",
    content_text: "갈증해소 뿐만이 아니라 기분까지 상쾌하게! 코카-콜라",
    M_img: "./menu_imgs/drink/coca_coke.png",
    L_price: 4700,
    M_price: 2900,
    set_Kcal: 185,
    Kcal: 133,
    weight: "425ml",
    suger: "33/33",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "9/0",
  },
  {
    id: 37,
    name: "코카-콜라 제로",
    en_name: "Coca-Cola Zero",
    data_type: "drink",
    content_text:
      "상쾌한 맛은 살리면서 웰빙 트렌드에 맞춰<br />설탕과 칼로리를 제로로 줄인 코카-콜라 제로",
    M_img: "./menu_imgs/drink/coca_coke_zero.png",
    L_price: 2900,
    M_price: 2400,
    Kcal: 0,
    weight: "425ml",
    suger: "0/0",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "34/2",
  },
  {
    id: 38,
    name: "스프라이트",
    en_name: "Sprite",
    data_type: "drink",
    content_text: "청량함에 레몬, 라임향을 더한 시원함!",
    M_img: "./menu_imgs/drink/sprite.png",
    L_price: 2900,
    M_price: 2400,
    Kcal: 140,
    weight: "425ml",
    suger: "35/35",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "28/1",
  },
  {
    id: 39,
    name: "환타",
    en_name: "Fanta",
    data_type: "drink",
    content_text: "톡 쏘는 오렌지 향!",
    M_img: "./menu_imgs/drink/FanTa.png",
    L_price: 2900,
    M_price: 2400,
    Kcal: 62,
    weight: "425ml",
    suger: "16/16",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "16/1",
  },
  {
    id: 40,
    name: "바닐라 라떼",
    en_name: "Vanilla Latte",
    data_type: "recommended_menu drink",
    content_text:
      "바로 내린 100% 친환경 커피의 진한 맛과 향,<br />1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
    M_img: "./menu_imgs/drink/Vanilla_Latte_hot.png",
    L_price: 5000,
    M_price: 4500,
    Kcal: 227,
    weight: "365ml",
    suger: "28/28",
    protein: "8/16",
    saturated_fat: "5/30",
    sodium: "79/4",
  },
  {
    id: 41,
    name: "카페라떼",
    en_name: "Café Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피가 신선한 우유를 만나<br />더 신선하고 부드럽게!",
    M_img: "./menu_imgs/drink/Café_Latte.png",
    L_price: 4500,
    M_price: 4000,
    Kcal: 149,
    weight: "365ml",
    suger: "9/9",
    protein: "8/14",
    saturated_fat: "5/30",
    sodium: "79/4",
  },
  {
    id: 42,
    name: "카푸치노",
    en_name: "Cappuccino",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피로 추출한 에스프레소<br />위에 갓 만든 우유 거품으로 더 부드럽게!",
    M_img: "./menu_imgs/drink/Cappuccino.png",
    L_price: 4500,
    M_price: 4000,
    Kcal: 93,
    weight: "365ml",
    suger: "6/6",
    protein: "5/8",
    saturated_fat: "2.9/19",
    sodium: "49/2",
  },
  {
    id: 43,
    name: "아메리카노",
    en_name: "Americano",
    data_type: "drink",
    content_text: "바로 내린 100% 친환경 커피로<br />더 신선하게! 더 풍부하게!",
    M_img: "./menu_imgs/drink/Americano.png",
    L_price: 3800,
    M_price: 3300,
    Kcal: 12,
    weight: "365ml",
    suger: "0/0",
    protein: "1/2",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 44,
    name: "드립 커피",
    en_name: "Drip Coffee",
    data_type: "drink",
    content_text: "100% 아라비카 원두를 드립 커피의 부드러움으로 만나보세요.",
    M_img: "./menu_imgs/drink/drip_coffee.png",
    L_price: 3200,
    M_price: 2700,
    Kcal: 10,
    weight: "365ml",
    suger: "0/0",
    protein: "1/1",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 45,
    name: "아이스 바닐라 라떼",
    en_name: "Iced Vanilla Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피의 진한 맛과 향,<br />1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
    M_img: "./menu_imgs/drink/Vanilla_Latte_ice.png",
    L_price: 5000,
    M_price: 4500,
    Kcal: 186,
    weight: "400ml",
    suger: "25/25",
    protein: "6/10",
    saturated_fat: "3.2/22",
    sodium: "50/3",
  },
  {
    id: 46,
    name: "아이스 카페라떼",
    en_name: "Iced Café Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피가 신선한 우유를 만나<br />더 신선하고 부드럽게!",
    M_img: "./menu_imgs/drink/Café_Latte_ice.png",
    L_price: 4500,
    M_price: 4000,
    Kcal: 108,
    weight: "400ml",
    suger: "7/7",
    protein: "5/10",
    saturated_fat: "3.2/22",
    sodium: "50/3",
  },
  {
    id: 47,
    name: "아이스 아메리카노",
    en_name: "Iced Americano",
    data_type: "drink",
    content_text: "바로 내린 100% 친환경 커피로<br />더 신선하게! 더 풍부하게!",
    M_img: "./menu_imgs/drink/Americano_ice.png",
    L_price: 3800,
    M_price: 3300,
    Kcal: 9,
    weight: "400ml",
    suger: "0/0",
    protein: "1/2",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 48,
    name: "아이스 드립 커피",
    en_name: "Iced Drip Coffee",
    data_type: "drink",
    content_text:
      "100% 아라비카로 풍부한 아로마의 드립 커피를<br />시원하게 만나보세요!",
    M_img: "./menu_imgs/drink/drip_coffee_ice.png",
    L_price: 3200,
    M_price: 2700,
    Kcal: 10,
    weight: "400ml",
    suger: "0/0",
    protein: "1/1",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 49,
    name: "디카페인 바닐라 라떼",
    en_name: "Decaffeine Vanilla Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피의 진한 맛과 향,<br />1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
    M_img: "./menu_imgs/drink/Vanilla_Latte_de.png",
    L_price: 5200,
    M_price: 4700,
    Kcal: 227,
    weight: "365ml",
    suger: "29/29",
    protein: "8/14",
    saturated_fat: "4/30",
    sodium: "85/4",
  },
  {
    id: 50,
    name: "디카페인 카페라떼",
    en_name: "Decaffeine Café Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피가 신선한 우유를 만나<br />더 신선하고 부드럽게!",
    M_img: "./menu_imgs/drink/Café_Latte_de.png",
    L_price: 4700,
    M_price: 4200,
    Kcal: 150,
    weight: "365ml",
    suger: "10/10",
    protein: "7/14",
    saturated_fat: "4.4/30",
    sodium: "85/4",
  },
  {
    id: 51,
    name: "디카페인 카푸치노",
    en_name: "Decaffeine Cappuccino",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피로 추출한 에스프레소<br />위에 갓 만든 우유 거품으로 더 부드럽게!",
    M_img: "./menu_imgs/drink/Cappuccino_de.png",
    L_price: 4700,
    M_price: 4200,
    Kcal: 89,
    weight: "365ml",
    suger: "6/6",
    protein: "5/8",
    saturated_fat: "2.5/17",
    sodium: "49/2",
  },
  {
    id: 52,
    name: "디카페인 아메리카노",
    en_name: "Decaffeine Americano",
    data_type: "drink",
    content_text: "바로 내린 100% 친환경 커피로<br />더 신선하게! 더 풍부하게!",
    M_img: "./menu_imgs/drink/Americano_de.png",
    L_price: 4000,
    M_price: 3500,
    Kcal: 12,
    weight: "365ml",
    suger: "0/0",
    protein: "1/2",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 53,
    name: "디카페인 아이스 바닐라 라떼",
    en_name: "Decaffeine Iced Vanilla Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피의 진한 맛과 향,<br />1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
    M_img: "./menu_imgs/drink/Vanilla_Latte_ice_de.png",
    L_price: 5200,
    M_price: 4700,
    Kcal: 191,
    weight: "400ml",
    suger: "26/26",
    protein: "6/10",
    saturated_fat: "3.2/22",
    sodium: "54/3",
  },
  {
    id: 54,
    name: "디카페인 아이스 카페라떼",
    en_name: "Decaffeine Iced Café Latte",
    data_type: "drink",
    content_text:
      "바로 내린 100% 친환경 커피가 신선한 우유를 만나 더 신선하고 부드럽게!",
    M_img: "./menu_imgs/drink/Café_Latte_ice_de.png",
    L_price: 4700,
    M_price: 4200,
    Kcal: 114,
    weight: "400ml",
    suger: "7/7",
    protein: "6/10",
    saturated_fat: "3.2/22",
    sodium: "54/3",
  },
  {
    id: 55,
    name: "디카페인 아이스 아메리카노",
    en_name: "Decaffeine Iced Americano",
    data_type: "drink",
    content_text: "바로 내린 100% 친환경 커피로 더 신선하게! 더 풍부하게!",
    M_img: "./menu_imgs/drink/Americano_ice_de.png",
    L_price: 4000,
    M_price: 3500,
    Kcal: 8,
    weight: "400ml",
    suger: "0/0",
    protein: "1/1",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 56,
    name: "바닐라 쉐이크",
    en_name: "Vanilla Shake",
    data_type: "dessert",
    content_text:
      "신선한 우유에 달콤한 바닐라 시럽으로 맛을 더한<br />깔끔한 쉐이크!",
    M_img: "./menu_imgs/drink/Vanilla_shake.png",
    M_price: 3500,
    Kcal: 366,
    weight: "425ml",
    suger: "55/55",
    protein: "9/16",
    saturated_fat: "5/36",
    sodium: "206/10",
    allergy:
      "알레르기 유발 가능 식재료 (우유)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 57,
    name: "딸기 쉐이크",
    en_name: "Strawberry Shake",
    data_type: "dessert",
    content_text:
      "신선한 우유에 상큼한 딸기 시럽으로 맛을 더한<br />부드러운 쉐이크!",
    M_img: "./menu_imgs/drink/Strawberry_shake.png",
    M_price: 3500,
    Kcal: 367,
    weight: "425ml",
    suger: "56/56",
    protein: "9/16",
    saturated_fat: "5/36",
    sodium: "180/9",
    allergy:
      "알레르기 유발 가능 식재료 (우유)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 58,
    name: "초코 쉐이크",
    en_name: "Chocolate Shake",
    data_type: "dessert",
    content_text:
      "신선한 우유에 달콤함 초코렛 시럽이 들어간<br />부드러운 쉐이크!",
    M_img: "./menu_imgs/drink/Chocolate_shake.png",
    M_price: 3500,
    Kcal: 375,
    weight: "425ml",
    suger: "55/55",
    protein: "9/17",
    saturated_fat: "5/37",
    sodium: "235/12",
    allergy:
      "알레르기 유발 가능 식재료 (우유)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 59,
    name: "생수",
    en_name: "Mineral Water",
    data_type: "drink",
    content_text: "활력을 되찾아주는 깔끔한 미네랄 생수.",
    M_img: "./menu_imgs/drink/water.png",
    M_price: 2000,
    Kcal: 0,
    weight: "500ml",
    suger: "0/0",
    protein: "0/0",
    saturated_fat: "0/0",
    sodium: "0/0",
  },
  {
    id: 60,
    name: "오레오 맥플러리",
    en_name: "Oreo McFlurry",
    data_type: "dessert",
    content_text:
      "우유 듬뿍 신선한 아이스크림에<br />아삭아삭 오레오 쿠키가 가득!",
    M_img: "./menu_imgs/dessert/Oreo_McFlurry.png",
    M_price: 4000,
    Kcal: 332,
    weight: "168ml",
    suger: "36/36",
    protein: "6/10",
    saturated_fat: "5.3/36",
    sodium: "179/9",
    allergy:
      "알레르기 유발 가능 식재료 (우유,대두,밀)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 61,
    name: "베리 스트로베리 맥플러리",
    en_name: "Very Strawberry McFlurry",
    data_type: "dessert",
    content_text:
      "신선한 1등급 원유에 국내산 딸기 과즙이 들어간<br />스트로베리 아이스크림에<br />오레오가 블랜드 되어 있는 맥플러리",
    M_img: "./menu_imgs/dessert/Strawberry_McFlurry.png",
    M_price: 4000,
    Kcal: 325,
    weight: "168ml",
    suger: "38/38",
    protein: "5/9",
    saturated_fat: "5.4/36",
    sodium: "228/11",
    allergy:
      "알레르기 유발 가능 식재료 (우유,대두,밀)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 62,
    name: "타로 파이",
    en_name: "Taro Pie",
    data_type: "dessert",
    content_text: "달콤한 보랏빛 디저트!<br />맥도날드 타로 파이",
    M_img: "./menu_imgs/dessert/tarot_pie.png",
    M_price: 2500,
    Kcal: 274,
    weight: "85g",
    suger: "10/10",
    protein: "2/4",
    saturated_fat: "4/26",
    sodium: "108/5",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 63,
    name: "불고기 버거",
    en_name: "Bulgogi Burger",
    data_type: "happyMill",
    content_text:
      "한국인의 입맛에 딱 맞는 불고기 소스에<br />잘 재운 패티와 고소한 마요네즈,<br />신선한 양상추의 맛있는 조합.",
    M_img: "./menu_imgs/happy_meal/bulgogiset.png",
    M_price: 5500,
    set_Kcal: "732~872",
    weight: "-",
    suger: "-",
    protein: "-",
    saturated_fat: "-",
    sodium: "-",
    allergy:
      "알레르기 유발 가능 식재료 (난류, 대두, 밀, 돼지고기, 조개, 굴, 우유, 대두, 토마토)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "돼지고기: 국내산,  함박패티: 덴마크산",
  },
  {
    id: 64,
    name: "맥너겟®4조각",
    en_name: "McNuggets® 4pcs",
    data_type: "happyMill",
    content_text:
      "바삭하고 촉촉한 치킨이 한 입에 쏙!<br />다양한 소스로 입맛에 맞게 즐겨보세요!",
    M_img: "./menu_imgs/happy_meal/McNugget_set.png",
    M_price: 5500,
    set_Kcal: "732~872",
    weight: "-",
    suger: "-",
    protein: "-",
    saturated_fat: "-",
    sodium: "-",
    allergy:
      "알레르기 유발 가능 식재료 (대두,밀,닭고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
  },
  {
    id: 65,
    name: "햄버거",
    en_name: "Hamburger",
    data_type: "happyMill",
    content_text:
      "00% 순 쇠고기 패티에 상큼한 피클과 양파,<br />기본에 충실한 맥도날드 햄버거.",
    M_img: "./menu_imgs/happy_meal/hamburger_set.png",
    M_price: 5500,
    Kcal: 266,
    weight: "-",
    suger: "-",
    protein: "-",
    saturated_fat: "-",
    sodium: "-",
    allergy:
      "알레르기 유발 가능 식재료 (난류,우유,대두,밀,돼지고기,토마토,쇠고기)<br />* 일부 튀김류 제품은 새우 패티와 같은 조리기구를 사용하고 있습니다.",
    country: "쇠고기:호주산",
  },
];
